apiVersion: v1
kind: Service 
metadata:
  name: deployment-svc 
  labels:
    purpose: deployment-practice
    project: roboshop
    environment: dev
spec:
  type: LoadBalancer
  selector:
    purpose: deployment-practice
    project: roboshop
    environment: dev
  ports:
  - protocol: TCP
    port: 80      # service port
    targetPort: {{ .Values.service.targetPort }}  # container port
